<?php
$server = "127.0.0.1";
$username = "root";
$password = "";
$database = "todo_list";
$connection = mysqli_connect($server, $username, $password, $database);
if ($connection->connect_errno) {
  die("connection failed" . $connection->connect_error);
}
//creating todo
if(isset($_POST['add']))
{
  $item=$_POST['item'];
  
  if(!empty($item)){
    $query="INSERT INTO todo (NAME) VALUES ('$item')";
    if(mysqli_query($connection,$query))
    {
      echo '<center>
      <div class="alert alert-success" role="alert">
        Item added successfully!
      </div>';
    }
  }
}
if(isset($_GET['action']))
{
  $itemid=$_GET['item'];
  
  if($_GET['action']=="done"){
    $query="UPDATE todo SET status = 1 WHERE ID='$itemid'";
    if(mysqli_query($connection,$query))
    {
      echo '<center>
      <div class="alert alert-info" role="alert">
      Item marked as done.
    </div>';
    }
    else{
      echo mysqli_error($connection);
    }
  }
  elseif($_GET['action']=="delete"){
    $query="DELETE FROM todo WHERE ID='$itemid'";
    if(mysqli_query($connection,$query))
    {
      echo '<center>
      <div class="alert alert-danger" role="alert">
      Item deleted successfully!
    </div>';
    }
    else{
      echo mysqli_error($connection);
    }
  }
}

?>
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Simple to do list</title>
  <link rel="stylesheet" href="todo.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <style>
    .done{
      text-decoration: line-through;
    }
  </style>
</head>

<body>
  <main>
    <!--
      <div class="alert alert-info" role="alert">
        Item marked as done.
      </div>
      <div class="alert alert-danger" role="alert">
        Item deleted successfully!
      </div>
    </center>-->
    <div class="card">
      <h5 class="card-header">To do list</h5>
      <div class="card-body">
        <form method="post" action="<?= $_SERVER["PHP_SELF"]?>">
          <div class="input-group input-group-lg">
            <span class="input-group-text" id="inputGroup-sizing-lg">Items</span>
            <input type="text" class="form-control" name="item" aria-describedby="inputGroup-sizing-lg" placeholder="Add a to do item">
            <input type="submit" class="btn btn-primary" name="add" value="Add Item">
        </form>
      </div>
      <div class="new1">

        <?php
        $query = "SELECT * FROM todo";
        $result = mysqli_query($connection, $query);
        if ($result->num_rows > 0) {
          $A = 1;
          while ($row = $result->fetch_assoc()) {
            $done=$row['STATUS']==1 ? "done" : "";
            echo '<div class="row">
                <div class="col-sm-12 col-md-1">
                  <h5>' . $A . '</h5>
                </div>
                <div class="col-sm-12 col-md-6">
                  <h5 class="'.$done.'">' . $row["NAME"] . '</h5>
                </div>
                <div class="col-sm-12 col-md-5">
                  <a href="?action=done&item=' . $row["ID"] . '" class="btn btn-primary">Done</a>
                  <a href="?action=delete&item=' . $row["ID"] . '" class="btn btn-danger" >Delete</a>
                </div>
              </div>';
            $A++;
          }
        } else {
          echo '<center>
                      <img src="download2.png" width="50px" style="margin-top: 20px;" alt="refresh"><br><span>Empty list</span>
                  </center>';
        }
        ?>
      </div>
    </div>
    </div>
  </main>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  <script>
    $(document).ready(function(){
      $(".alert").fadeTo(500,50).slideUp(500,function(){
        $(".alert").slideUp(50);}
    )
    })
  </script>
</body>

</html>